### ISSUE TITLE
Create GitHub action to test new code before merging

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#232]
### Background on the problem the feature will solve/improved user experience
Add GitHub Actions to test and build new code pushed to a branch or committed to a pull request. Code that passes all the steps in the GitHub action can be merged in the repository.

### Describe the solution you'd like
A GitHub action runs whenever code is committed to any branch or PR is made to the main branch. 
- [ ] services folder

Refer to a similar action that was implemented for the[ UI folder.](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/main/.github/workflows/build-ui.yml)

Each action will 
- [ ] install dependencies (`yarn install`)
- [ ] build for production (`yarn build`)
- [ ] run all tests (`yarn run test:unit`)
- [ ] linting with [prettier](https://prettier.io/docs/en/index.html) (`yarn run lint`)

### Tasks
- [ ] Ensure install, build and lint steps run locally on your system
- [ ] Read more about [GitHub actions](https://docs.github.com/en/actions/learn-github-actions) 
- [ ] You can read more [JavaScript build actions here](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python).
- [ ] Commit and push your GitHub action code.
- [ ] Go to the [Actions tab](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/actions) to see if it worked.

### Acceptance Criteria 
GitHub action runs for every new code commit and PR.

FYI @demilolu @davidnixon

**Comment by upkarlidder** [comment]
Go for it @gibrankasif!

FYI @demilolu @davidnixon @GeraldMit
