### ISSUE TITLE
Enable pre-commit hooks

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#285]
### Background on the problem the feature will solve/improved user experience
Add pre-commit hook support

### Describe the solution you'd like
Add the husky package to enable git hooks for developers

### Tasks 
Referencing this doc [install husky](https://typicode.github.io/husky/#/?id=yarn-2)
And this doc [npm husky](https://www.npmjs.com/package/husky)

- [ ] Add the husky package
    ```sh
    cd Five-Fifths-Voter/ui
    yarn add husky --dev
    ```
    edit the package.json and add this to the scripts section
    ```json
    "postinstall": "cd .. && husky install"
    ```
    run the install
    ```sh
    yarn postinstall
    ```
- [ ] Repeat those steps with the `database` and `services` directory
- [ ] Add a "hello world" hook
  ```
  cd Five-Fifths-Voter
  npx husky add .husky/pre-commit "echo hello husky"
  git add .husky/pre-commit
  git commit -s -m "Keep calm and commit"
  # you should see hello husky
  ```

### Acceptance Criteria 

Hooks should be enabled when "yarn" is run in the `ui` dir or `database` and `services` directory
git commit should show "hello husky" for all commits.

**Comment by davidnixon** [comment]
@upkarlidder added this issue to narrow the scope of #168 after we have this enabled we can add more pre-commit tests
