### ISSUE TITLE
Early voting in Georgia election

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#336]
### Background on the problem the feature will solve/improved user experience
As a voter in Georgia, I have to do deal to decide if I should vote early or employ another means of voting.

### Describe the solution you'd like

Information that includes

- [ ] my polling site
- [ ] dates/times I can vote at the polling site
- [ ] when early voting is 
- [ ] voting ID requirements

see box note to determine links to use - https://ibm.ent.box.com/notes/985555838518

### Tasks 
- Decide on which resource is our generic source of truth
- Decide how to link/display information on our site
