### ISSUE TITLE
Mail-in ballot in Georgia election - GA site launch

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#338]
### Background on the problem the feature will solve/improved user experience
As a voter in Georgia, I'm faced with confusing mail-in ballot rules and deadlines. These include the new rule that I must request for a ballot.  I need to have all the information I need in an easy to understand format. 

### Describe the solution you'd like

Information that includes

- [ ] How to submit a mail-in ballot request online , in person via email
- [ ] calendar of dates (and links)
          - earliest date  to request a ballot ( August 22nd)
          - latest date to request ballot (11 calendar days before election)
          - earliest date registrar will mail UOACVA ballot (Sep 20)
          - earliest date registrar will mail regular absentee ballot (October 10)
          - latest date ballot can be received
          - 
- [ ] how to properly fill out and return a ballot
- [ ] how to check ballot status 
- [ ] voting ID requirements for mail-in ballots
- [ ] Ballot drop off locations & times (some/all? are early voting sites) 

see box note to determine links to use - https://ibm.ent.box.com/notes/985555838518

### Tasks 

- [ ] Again, show GA info if we detect GA
- [ ] Change or recrop the right imageto be same size as image on other pages

Show:

- [ ] x days to request mail in ballot. Deadline Oct 28
- [ ] Link to request a ballot
- [ ] x days before you can request a ballot. Earliest day is Aug 22.
- [ ] Laws have changed since last election. A drivers license or other id is required.
- [ ] Checkbox: check here if you plan to vote early or you have requested your absentee ballot
