### ISSUE TITLE
Election Day voting in Georgia election 

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#339]
### Background on the problem the feature will solve/improved user experience
As a voter in Georgia, I  need to know how to vote on Election Day

### Describe the solution you'd like

Information that includes

- [ ] my polling site
- [ ] times I can vote at the polling site
- [ ] voting ID requirements for in-person voting

see box note to determine links to use - https://ibm.ent.box.com/notes/985555838518

### Tasks 
- Decide on which resource is our generic source of truth
- Decide how to link/display information on our site
