### ISSUE TITLE
Location API to route user to voter journey page - GA site launch

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#347]
### Background on the problem the feature will solve/improved user experience
As a user when I land on the site I should be directed to the information relevant to my location. 

### Describe the solution you'd like

- [ ] Let the location API gather information for a few seconds
- [ ] Then automatically route user to the Voter Journey pages
- [ ] User is free of course to navigate back to the home page

### Tasks 
Description of the development tasks needed to complete this issue, including tests, 

- [ ] Install location API: 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.
