### ISSUE TITLE
Post Voter Registration deadline landing page - GA site launch

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#348]
### Background on the problem the feature will solve/improved user experience
As a visitor when I visit Five Fifths Voter after the voter registration deadline I should get up to date information.

### Describe the solution you'd like
"Get Informed" is the landing page after Oct 11 registration deadline or if the user has
checked the box "I'm registered" on previous page 
<img width="669" alt="post registration landing page" src="https://user-images.githubusercontent.com/3202514/187722576-253b01a8-4e07-4abb-bb33-e2503d89082c.png">

Show Links to candidates in top races (GA)

- [ ] ● Governor
- [ ] ● Lieutenant Governor
- [ ] ● Secretary of State
- [ ] ● Attorney General
- [ ] ● Superintendent of Public
- [ ] ● Agriculture Commissioner
- [ ] ● LaborCommissioner
- [ ] ● Insurance Commissioner
- [ ] ● U.S.Senator
- [ ] ● U.S.House of Representatives

### Tasks 
Description of the development tasks needed to complete this issue, including tests, 

### Acceptance Criteria 

- [ ] Utilize non-partisan sites as possible for each candidate
