### ISSUE TITLE
Post midterm 2022

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#363]
### Background on the problem the feature will solve/improved user experience
After the midterms are over, the navigation needs to revert back to the default home page. Also the countdown clock should revert to the 2024 presidential election.

### Describe the solution you'd like
Default to land on home page
New clock

### Tasks 

- [x] create new json file for 2024 presidential election. Should just have generic information for all states.
- [x] Check countdown clock
- [x] Check navigation lands on home page
- [x] Check journey pages to see that proper dates etc are displayed

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.
