### ISSUE TITLE
Add Instagram button

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#365]
### Follow 
Add link to follow 5/5 Instagram channel

### Describe the solution you'd like
A button on the home page or maybe in the header

### Tasks 

- [x] UI design (or else this will be dev designed) :-1: 
- [x] Find examples on the web of similar buttons
- [x] Research how to implement
- [x] Implement button

### Acceptance Criteria 
Click button open Instagram to 5/5 feed

**Comment by davidnixon** [comment]
link is https://instagram.com/fivefifthsvoter?igshid=Zjc2ZTc4Nzk=

**Comment by iamvinayvk** [comment]
@davidnixon I have raised the PR can you please review it.

**Comment by GeraldMit** [comment]
Thank you @iamvinayvk ! looks great.
